# Generated by Django 5.1.6 on 2025-02-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, default='path/to/default/image.jpg', null=True, upload_to='movies/posters/'),
        ),
    ]
